# What is PyTorch?

https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

## Getting Started


### Tensors


Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -2.0000e+00,  1.8041e+25],
        [-1.5849e+29,  5.6052e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  9.8303e-13, -9.9054e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


Construct a randomly initialized matrix:



In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6165, 0.2122, 0.5577],
        [0.4947, 0.1536, 0.7310],
        [0.9719, 0.7535, 0.8391],
        [0.9520, 0.8395, 0.6468],
        [0.0406, 0.4216, 0.0254]])


Construct a matrix filled zeros and of dtype long:



In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.7626,  0.3739, -0.9904],
        [-0.2911, -2.5123,  1.7623],
        [-0.7626, -1.3244, -0.6115],
        [ 0.5287,  0.3650, -1.8393],
        [-0.9112,  0.1633,  0.6396]])


Get its size:



In [7]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

### Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1

In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.3234,  0.9840, -0.0878],
        [ 0.0635, -1.6555,  1.9912],
        [-0.3449, -1.1035, -0.1158],
        [ 1.1251,  1.1009, -1.0983],
        [-0.8660,  0.3016,  0.8568]])


Addition: syntax 2



In [9]:
print(torch.add(x, y))

tensor([[-0.3234,  0.9840, -0.0878],
        [ 0.0635, -1.6555,  1.9912],
        [-0.3449, -1.1035, -0.1158],
        [ 1.1251,  1.1009, -1.0983],
        [-0.8660,  0.3016,  0.8568]])


Addition: providing an output tensor as argument



In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.3234,  0.9840, -0.0878],
        [ 0.0635, -1.6555,  1.9912],
        [-0.3449, -1.1035, -0.1158],
        [ 1.1251,  1.1009, -1.0983],
        [-0.8660,  0.3016,  0.8568]])


Addition: in-place



In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.3234,  0.9840, -0.0878],
        [ 0.0635, -1.6555,  1.9912],
        [-0.3449, -1.1035, -0.1158],
        [ 1.1251,  1.1009, -1.0983],
        [-0.8660,  0.3016,  0.8568]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [12]:
print(x[:, 1])

tensor([ 0.3739, -2.5123, -1.3244,  0.3650,  0.1633])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.3003])
0.3002583682537079


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  [here](https://pytorch.org/docs/torch).

## NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

## CUDA Tensors

Tensors can be moved onto any device using the ``.to`` method.

In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!